# Generated by Django 2.2 on 2022-01-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_projectlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('project', models.ManyToManyField(to='projects.Project')),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
    ]
