# Generated by Django 2.2 on 2022-01-26 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20220125_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_actual_design', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('changed_actual_design', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_actual_design', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('initial_actual_development', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('changed_actual_development', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_actual_development', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('initial_actual_testing', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('changed_actual_testing', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_actual_testing', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'project_logs',
            },
        ),
    ]
